---
title: "Living Landscapes Lab Mentor-Mentee Compact "
output:
  html_document:
    # toc: false
    # toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    includes:
       in_header: [g_analytics.html,header_pubs.html]
    css: front.css
---

## OVERVIEW 

This mentor-mentee compact outlines 1) what you as a graduate student mentee can expect from me, 2) what I as a mentor expect from you, and 3) other important details about data, authorship, etc. If you are a Living Landscapes member, will be a member soon, or are interested in joining, please read this compact carefully. This is not a contract. It is a living document, meaning it can and will evolve with your input and my experience. I’m looking forward to working with you, getting amazing conservation research done, and supporting your professional growth! 

### WHAT TO EXPECT FROM ME 

Overall, my goal is to help students develop into colleagues in the natural resources management field. That’s what the USGS Coop Units are all about! 

- **I will respect all students as individuals without regard to gender, race, national origin, religion, disability, health issues, or sexual orientation, and I will foster a climate of positivity in the lab.** I will also not tolerate harassment based on any of these things. 
- **I will be committed to help provide financial resources for the graduate student to conduct their thesis/dissertation research.** I will discuss and agree to funding details with students prior to hiring them. Normally, I will only hire students when I have grant funds to support RA (meaning the student doesn’t have to teach to support themselves). However, if funding changes, I will notify students the semester before they need to TA. 
- **I will be committed to each student’s research project.** I will work with each student to help guide and plan the research project, set attainable goals, and a timeline for completion of the project. 
- **I will be committed to meeting one-on-one with students on a regular basis.** I will regularly review student progress and provide timely feedback and goal setting advice. I will make time to have weekly one-on-one meetings with students in addition to weekly lab meetings. Also, if my door is open, please pop in and ask questions. I’m here to help.  
- **If I am concerned about a student’s research progress or other work-related issues, I will quickly and directly address issues with the student.** If I notice a pattern of poor research productivity, time management, or issues with how students interact with Cooperators or fellow lab members, I will address these in a timely manner through a one-on-one conversation. We can jointly make a plan to get back on track. 
- **I will promote student training in professional skills needed for a successful career.** These skills include oral and written communication, writing grants (this will mostly be for/with PhD students), time management, collaborative research, networking, working with Cooperators and practitioners, teaching, and mentoring. I will encourage the student to seek opportunities to develop skills in these areas outside the lab as well. 
- **I will encourage and foster each student’s professional network.** I will help guide students, if necessary, in finding appropriate external mentors, particularly in the fields and organizations that the student is interested in working for. These external mentors will be your network as you move forward in a scientific career. However, it is up to YOU to cultivate these relationships. 
- **I will set an example for work-life balance.** Just like you, I have a life outside of work. I love spending time with my family, traveling, running, reading, hiking, camping, playing board games/table-top RPGs, gardening, and cooking. To make sure I can do all those things, I try to work efficiently during “normal” business hours (0800 – 1630 CT weekdays). That means I will likely not answer emails outside of those times, unless it’s an emergency.  

### WHAT I EXPECT FROM YOU 

#### Professional interactions 

- The first rule of our lab is to be respectful to everyone.  
- The second rule is that students will be professional in all interactions with the Unit’s Cooperators (Arkansas Game & Fish Commission, US Fish & Wildlife Service, US Geological Survey, University of Arkansas). This means that students will meet their obligations to Cooperators, attend required Cooperator meetings, and always seek to present a good image to our Cooperators. This is foundational to the Coop Unit program. 
- I expect you to write professional e-mails. 
- If you are taking the lead on communicating with other groups outside of the lab for a research project, I will set up the initial interaction. I may ask the student to lead subsequent interactions. I expect to be ‘ccd on important e-mails. You are responsible for identifying ahead of time what constitutes an “important communication.” 

#### Lab interactions 

- Treat other lab members with respect. 
- You will be an active contributing member to all team efforts and collaborations and will respect individual contributions. You will contribute to an environment that is safe, equitable, and free of harassment. 
- You are encouraged to participate in lab-wide fun activities and to foster a fun and welcoming lab community. For example, I host cookouts at my house ~2 times each year. We celebrate when lab mates graduate or have major achievements. We sometimes go on hikes or field site visits as a lab. 
- If you have issues with a particular lab member, think about the best way to approach the situation. When you are calm, try to initiate a conversation about your frustrations and resolve the issue. If you need help managing these situations, talk to me. 

#### Work habits, organization, and time management 

- You have the primary responsibility for successfully completing your degree. This includes commitment to your work in class and in the lab. You should maintain a high level of professionalism, motivation, engagement, scientific curiosity, and ethical standards. 
- Attend and be prepared for our one-on-one meetings and lab meetings. I provide my best feedback when students organize questions, data, results, presentations, and writing before meeting with me. I expect students to drive one-on-one meeting agendas. IMPORTANT: I can’t provide feedback if you don’t give me something tangible to review. 
- Try to figure out answers on your own before approaching me. Bend your considerable ingenuity to finding answers from your lab mates, the internet, etc. You’re an aspiring scientist, and you can totally do this! However, I’m absolutely here to help and answer questions. I don’t want you to waste too much time spinning your wheels, so if you feel like you’re completely stumped with writing, coding, study design, etc., let me know! 
- Know and comply with the policies, deadlines, requirements of the graduate program, school, university, and Arkansas Coop Unit. Complete all your USGS safety trainings, university trainings, etc. in a timely manner. Graduation, enrollment, registration, deadlines, and requirements can change, and it is your responsibility to stay apprised. - Be present in the office during normal-ish business hours at least 2 – 3 times weekly. Normal-ish business hours in my lab are 0800 – 1630 CT Monday through Friday, although I do not require students to come and leave at a defined time each day. The obvious exceptions are during the student’s field season, vacation, and university closures. Taking breaks, working odd hours, etc. is okay. That’s grad school life! But if you are not disciplined and multitasking, it can take you 60 hours to complete what a disciplined student can in 40 hours. I expect people are actively working ~ 40h per week (reading, etc. is part of this). Sometimes it is necessary to put in extra time to meet deadlines. 
- Strive to meet deadlines and manage your progress.  
- Organize your work for each week, semester, and year. Create and maintain a list of short-, medium- and long-term goals with deadline to keep you on track. Calibrate your lists to make them attainable so you don’t burn out, but also be ambitious. Time never stands still, and things (particularly writing) always take longer than you think they will. 
- Strive for a healthy work-life balance. You are more than your work and research. Do something that gives you joy every day. Get enough sleep. Embrace and grow your mental, physical, and spiritual health. Research is a long game, and a centered person can be more disciplined, creative, and productive. 

#### Holidays, Breaks, and Vacation 

- Students are not expected to work when the university is closed for holidays or breaks. These holidays and breaks are defined by the University of Arkansas.  
- Each student also has 2 additional weeks of vacation a year. Importantly, this is a Living Landscapes Lab policy—not a university policy. Let me know as far ahead of time as possible if/when you will be going on vacation. I require a written request 1 month in advance of a one-week vacation, and longer if you plan on taking all your vacation at once. You are responsible for organizing the care of your experiments, fieldwork, classes, etc. during your vacation. I reserve the right to not approve vacation requests if deadlines are not being met, Cooperator relationships are on the line, etc. Graduate students do not get summers off or spring break off: students need to request vacation if they want time off during summer or spring break (see the official university holidays and closures). 

#### Authorship, Publications, and Sharing Materials 

- I typically do not decide order of authorship at the beginning of a project. Things can change over time and some individuals may end up contributing more than others. When it is clear we have a publishable story that is over half finished, I will meet with the group and we can decide authorship order. 
- I expect the first author to perform most of the work, take the lead on writing the paper, and take the lead on journal revisions. I will work with each student to help plan how to write each section, sketch out figures, provide general feedback, and polish each paper. 
- We adhere to the Ecological Society of America’s authorship criteria. 
- Students will adhere to all USGS FSP policies. If you don’t know what this is, ask me for instructions. 
- Before submitting any paper, I require all computer code to be annotated and placed in a shared OneDrive folder. I also require metadata files for all data. 

 

NOTE: Inspired by Coaker Lab Compact (https://www.coakerlab.org/mentoring-compact--graduate-student.html) 

