---
title: "People"
output:
  html_document:
    includes:
      in_header: g_analytics.html
  # pdf_document: default
---

Lab members listed alphabetically by last name. Last updated: November 28, 2023.

```{r, echo = FALSE, include = FALSE}
# List of packages necessary to run this script:
library(librarian)
shelf(data.table, stringr, magrittr, dplyr, kableExtra, knitr)

```

```{r, include = TRUE, echo = FALSE}

# get file names/locations for profile pictures
profile_pics <- sort(paste0("C:/Users/cr065/Documents/GitHub/LivingLandscapes_Website/images/ProfilePics/",
                            list.files("C:/Users/cr065/Documents/GitHub/LivingLandscapes_Website/images/ProfilePics")),
                     decreasing = TRUE)

# Sort profile pics
profile_pics <- data.table(profilePicFiles = profile_pics,
                           sortPics =   sapply(str_extract_all(str_remove(str_remove(profile_pics, 
                                            "C:/Users/cr065/Documents/GitHub/LivingLandscapes_Website/images/ProfilePics/ProfilePic_"), 
                                         "\\.([A-Z]+)|\\.([a-z]+)"), 
                              "[A-Z][a-z][a-z]"), function(X) X[2]))[order(sortPics)]
profile_pics <- unlist(profile_pics$profilePicFiles)



# Create data.frame with lab member info
people_tbl <- data.frame(
  Members = c("Caleb Roberts", "Paul Akpejeluh", "Vinita Karki", "Michael Ferrara", "Mike Shaw", "Jess Schmit", "Lauren Berry", "Ken Wilson", "Lindsey LaBrie"),
  Roles = c("PI", "PhD Student", "PhD Student", "Master's Student", "Master's Student", "Master's Student", "Master's Student", "Master's Student", "PhD Student"),
  Contact = c("cr065@uark.edu", "paulakpejeluh23@gmail.com", "vinicarkey8@gmail.com", "mcferrara44@gmail.com", "ms161@uark.edu", "jmschmit@uark.edu", "llberry@uark.edu", "kw101@uark.edu", "llabrie@uark.edu"),
  Bios = c(
    "Caleb is the leader of the Living Landscapes Lab. He works for the U.S. Geological Survey as an Assistant Unit Leader at the Arkansas Cooperative Fish & Wildlife Research Unit. Caleb's research interests include ecological resilience, grasslands, landscape ecology, fire, birds, invasive species, plants, community ecology, agroecosystems, complexity theory, and rangelands. Caleb is from western Kentucky, and he enjoys writing, running, reading, cooking, gardening, board games, hiking, and hanging out with his wife, daughter, and cat.",
    "Bio and picture coming soon! (Photo credit: ‘Baby Roosevelt Elk’ by goingslo is licensed under CC BY-NC-ND 2.0.)",
    "My research interests encompass ecological modeling, geospatial mapping, and the conservation and management of avian species. I will join the Living Landscape lab to pursue a PhD. My dissertation research will be to create a comprehensive statewide decision support tool for wild turkey conservation efforts in Arkansas. Ultimately, by pinpointing the areas where our efforts can have the most positive impact on turkey populations in Arkansas, we can make a substantial contribution to their management. I did my master's in Biological Sciences from Fort Hays State University, and my thesis used Motus Wildlife Tracking Network to estimate population size and understand fine-scale local movements of migratory birds in the Cheyenne Bottoms, KS. In addition to my research pursuits, I enjoy backpacking, hiking/trekking, and bird watching. Having grown up in a mountainous region, I eagerly anticipate the opportunity to delve into the rugged beauty of the Ozarks mountains.",
    "Michael will be studying how birds use solar panel arrays with understories of native grasses and forbes compared to those with turf grass. He is passionate about species and ecosystem conservation. His primary research interests are in population dynamics, interspecies interactions and habitat use to protect species of concern. Michael received his B.S. from SUNY College of Environmental Science and Forestry and since then has been working with avian species across the eastern United States. He is originally from Long Island, New York and in his free time, he enjoys hiking, birding, photography, traveling, cooking, playing video games and watching sports.",
    "Mike’s research interests are in mammal ecology, and he will be studying Eastern Spotted Skunk (Spilogale putorius) in southwest Arkansas. He will be using camera traps to document the presence of Eastern spotted skunk and observe habitat associations. Mike worked in Colorado as a wildlife technician for Colorado Parks and Wildlife and moved to Maryland after his position in Colorado. In Maryland, he worked for county government as a wildlife management specialist. Mike is from eastern Maine, and he enjoys hiking, weightlifting, kayaking, and boardgames.",
    "Jess is incredibly excited to be joining the Living Landscapes Lab as a Masters’ student studying King Rails in Arkansas.  Her research interests are avian and wetland ecology, endangered species, habitat selection and resiliency in relation to climate change. Jess’ project will focus on King Rail breeding,  ecology, distribution and abundance in Arkansas, as well as their site selection and habitat use. She has been working as a wetland bird field technician for the last five years and has been blessed to work with a variety of species. Her last three years of work have been focused on rails, and she loves the challenge of working with these intelligent birds. Jess has a mailing address in Pennsylvania but is hardly home! When she isn’t in the field, she enjoys reading, kayaking, finding great local breakfast places wherever she lives, and hanging out with her husband and cat.",
    "Lauren’s research interests include conservation management, population ecology, and avian ecology in response to our changing land use and climate. She is joining the Living Landscapes Lab to work on a project that will use data collected in and near three USFWS National Wildlife Refuges to create a mapping tool to quantify grassland bird and habitat core responses to grassland management. She has just finished her undergraduate work at Hendrix College, where she worked on a variety of projects including surveying urban wildlife in Central Arkansas, banding passerines at a Monitoring Avian Productivity and Survivorship station, and using Long Term Ecological Research Site data to evaluate insect population trends across North America. An Arkansas native, Lauren loves to backpack, cook, read, write, and spend time with her family in the southeastern part of the state.",
    "Ken’s research is focused on ground and shrub nesting birds in Southern Arkansas, and how they are impacted by the presence of feral hogs. Using camera traps, point count surveys, and vegetation surveys, Ken will measure the diversity and occupancy of breeding birds in bottomland hardwood floodplains and upland pine forests and how this is related to the density of feral hogs. This study will help us better understand how to manage a highly invasive species to protect vulnerable bird populations. Ken has previously worked for federal and state wildlife agencies studying secretive wetland birds, ground-nesting warblers, and pygmy owls, among other avian species. Ken is from New Jersey and in his free time, he enjoys reading, hiking, martial arts, and spending time with his cat.",
    "Lindsey is interested in invasive species ecology of riverine ecosystems, especially in the context of climate change. In the Living Landscapes Lab, she will be researching differences in invasive species management policies across the country, determining invasion potential for various aquatic nuisance species throughout the state of Arkansas, and estimating future invasion risks using climate change models and horizon mapping techniques. She completed her M.S. in Biology at the University of South Dakota in May 2023. She received a B.S. in Fisheries & Wildlife and a B.A. in German Language & Literature from the University of Nebraska-Lincoln in May 2020. Lindsey is originally from Hastings, Nebraska. When she's not on the river or thinking about fish, you'll find her drinking coffee, gardening, painting, cooking, rollerblading, camping, indoor rock climbing, or snuggling with her cat Jinx."
  ),
  Pics = rep("", length(profile_pics))
)

# Order lab member data.frame alphabetically
people_tbl <- 
  people_tbl %>%
  mutate(Surname = str_trim(str_extract(Members, "(\\ [A-Z][a-z])")))
people_tbl <- as.data.table(people_tbl)[order(Surname, decreasing = FALSE)][ , "Surname" := NULL]

# Remove column names
setnames(people_tbl, names(people_tbl), rep("", ncol(people_tbl)))

# Create html table with people info
kbl(people_tbl) %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = TRUE, border_right = FALSE, 
              width = "10em") %>%
  column_spec(2, bold = FALSE, border_right = FALSE, width = "15em") %>%
  column_spec(3, bold = FALSE, border_right = FALSE, 
              width = "5em") %>%
  column_spec(4, width = "20em") %>%
  column_spec(5, width = "30em", image = profile_pics)


```