---
title: "News"
css: notitle.css
self_contained: true
output: 
  html_document:
    includes:
       in_header: [open_parent.html]
---


<style type="text/css">

body, td {
  font-size: 12px;
}

</style>

<!-- --- -->

<!-- December 2023 -->

<!-- - Congratulations to **Mike Shaw** for passing his thesis defense!!! Mike will be heading to Michigan State to pursue a PhD. We'll miss you, Mike! -->

---

November 2023

- So excited for our two new additions to the lab: **Vinita Karki** and **Michael Ferrara**! Vinita will be creating a statewide decision support tool to inform wild turkey conservation, and Michael will be joining the WildSNaP project to investigate the responses of bird communities to native plantings under solar arrays. Check out the [People](https://livinglandscapes.github.io/LivingLandscapes_Website/People.html) tab to read their bios and the [Research](https://livinglandscapes.github.io/LivingLandscapes_Website/Research.html) tab to read about their projects.

---

October 2023

- We have a new publication led by [Dr. Tori Donovan](http://www.victoriamdonovan.org/) of UFL on fire, cheatgrass, and eastern Ponderosa pine forests! Check it out in [Plant Ecology](https://link.springer.com/article/10.1007/s11258-023-01355-9).

---

September 2023

- +1 publication for September: Caleb is a coauthor on the [fire chapter](https://link.springer.com/chapter/10.1007/978-3-031-34037-6_6) in the new, open-access [Rangeland Wildlife Ecology and Management](https://link.springer.com/book/10.1007/978-3-031-34037-6#toc) book!
- Our first lab project manuscript was published in [Restoration Ecology!](https://onlinelibrary.wiley.com/doi/full/10.1111/rec.13998?casa_token=oaVpK3sps0EAAAAA%3APonfiF3LJv1APdTmslZilCYq9t0N5ULmadjIRjf-FEXne7-O8a-7h4Z-vojLfNyrzTgp9tE6s7zQSOaT).
- Also, Caleb is teaching Ecological Modeling this semester! Check out the [course website](https://livinglandscapes.github.io/Course_EcologicalModeling/). We're building it as the semester progresses, so keep an eye out for updates if you're interested in learning statistics.

---

August 2023

- [**1 MS position open in the lab!](https://livinglandscapes.github.io/LivingLandscapes_Website/Opportunities.html): Come investigate how birds are responding to native plantings under solar arrays! Fully funded, lots of field work, and opportunities to work with renewable energy, acoustic recording units, and a fantastic team of scientists!
- We're so excited that [Lindsey LaBrie](https://livinglandscapes.github.io/LivingLandscapes_Website/People.html) will be joining the Living Landscapes Lab this fall! Lindsey will be pursuing a PhD and leading research on aquatic invasive species. Can't wait!
- Congratulations to our very own [Jess Schmit](https://wilsonsociety.org/awards/student-presentation-awards/lynds-jones-prize/) for winning the 2023 Lynds Jones Prize for best poster at the 104th Annual Meeting of the Wilson Ornithological Society! King Rails all the way!
- And last, but definitely not least, congratulations to Percy Marshall for graduating with their M.S.! Thankfully, we're keeping Percy around for a bit to help design a study on invasive shrub treatments at Big Oaks NWR--and to finish publishing their amazing thesis chapters.

---

June 2023

* [**2 PhD positions open in the lab**](https://livinglandscapes.github.io/LivingLandscapes_Website/Opportunities.html):
  + *Wild Turkey Population Ecology*: Want to study wild turkeys and learn about Integrated Population Models and spatially varying coefficient models? Start date is spring 2024!
  + *Invasion Ecology*: Also, we have an amazing position investigating new methods for early detection of invasive plant species + impacts of invasive plant species. If you're interested in modeling, fire ecology, wildlife, and/or ecosystem services, we hope to see your application in the pool! Start date is fall 2023 or spring 2024.

---

April 2023

- +1 Ph.D. student position: Come push the field of *early detection* of invasive species forward and work with a diverse group of amazing scientists from [USDA ARS Northern Plains Agricultural Research Laboratory](https://www.ars.usda.gov/plains-area/sidney-mt/northern-plains-agricultural-research-laboratory/pest-management-research/people/carissa-wonkka/), [USDA ARS Livestock and Range Research Laboratory](https://www.ars.usda.gov/people-locations/person?person-id=56276), [University of Florida](https://wfrec.ifas.ufl.edu/directory/dr-victoria-donovan/), [USGS](https://www1.usgs.gov/coopunits/staff/1397482), [USFS](https://www.srs.fs.usda.gov/staff/412), and [Michigan State University](https://www.jeffdoser.com/)! Check out our [Join The Lab tab](https://livinglandscapes.github.io/LivingLandscapes_Website/Opportunities.html) for more info.

---

March 2023

- Congratulations to Percy Marshall for winning second place in the Arkansas Chapter of The Wildlife Society's Student Oral Presentation Award! We're so proud!
- We're heading to [IALE-North America](https://www.ialena.org/) next week! Hope to see you there! 

---

January 2023

- We're hiring a Ph.D. student to work on aquatic invasive species issues in Arkansas and beyond! To apply, see the job ad in the [Join The Lab tab](https://livinglandscapes.github.io/LivingLandscapes_Website/Opportunities.html). Looking forward to seeing your application!
- Speaking of invasive species--stay tuned for *another* Ph.D. student position opening soon! Some sneak peaks: there's gonna be study sites in Florida/Arkansas, visits to Montana, learning about fire, and creating a national-scale early detection workflow for invasive terrestrial plants. Can't wait!!

---

December 2022

- "America’s Billion-Dollar Tree Problem Is Spreading". Now that's a catchy headline. Check out the [Wired magazine](https://www.wired.com/story/billion-dollar-encroaching-tree-problem/) that covers our [Journal of Applied Ecology](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.14288) and [Journal of Environmental Management](https://www.sciencedirect.com/science/article/pii/S0301479722019326?dgcid=author) articles! 

---

November 2022

- How much does tree invasion of grasslands cost western US economies? Billions. Check out our new [Journal of Applied Ecology](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.14288) article for the details.
- Our own [Percy Marshall](https://livinglandscapes.github.io/LivingLandscapes_Website/People.html) has published their first peer-reviewed manuscript in [Crop Science](https://www.sciencedirect.com/science/article/pii/S0261219422002125)! Spoiler: hummingbirds can help control orchard pest insects!

---

October 2022

- New technologies allow us to rapidly learn from rangeland management actions like prescribed fire, grazing, and tree removal at scales from 30m2 pixels to biomes! Check out our brand new [Journal of Environmental Management](https://www.sciencedirect.com/science/article/pii/S0301479722019326?dgcid=author) manuscript to learn more.
- We're kicking off a new research project on risk of [giant salvinia](https://www.invasivespeciesinfo.gov/aquatic/plants/giant-salvinia) invasion. See our [research tab](https://livinglandscapes.github.io/LivingLandscapes_Website/Research.html) to learn more!

---

August 2022

- [Ken Wilson](https://livinglandscapes.github.io/LivingLandscapes_Website/People.html) joined the Living Landscapes Lab this fall! Ken will be quantifying feral hog impacts on vegetation and ground-nesting birds in southeastern Arkansas USFWS refuges. Welcome, Ken!
- Speaking of Ken's project, check out the new project we're kickstarting this fall: [Assessing Wild Pig Impacts to Ecosystem Services: A Case Study on Diet, Density, and Space Use of Wild Pigs on the South Arkansas National Wildlife Refuge Complex](https://livinglandscapes.github.io/LivingLandscapes_Website/Research.html). This is a USFWS/USGS funded project, and we're very excited to get into the messy world of feral hogs.

---

July 2022

- [Audubon Magazine](https://www.audubon.org/magazine/summer-2022/in-nebraskas-loess-canyons-setting-trees-ablaze) just covered our fire-grassland bird restoration research! Many thanks to the Working Land for Wildlife folks who are getting the good word out!

---

June 2022

- We're very excited to welcome [Lauren Berry](https://livinglandscapes.github.io/LivingLandscapes_Website/People.html) to the Living Landscapes Lab! Lauren will be using bird community and remote sensing data to quantify grassland management outcomes for USFWS refuges.
- Super excited that National Public Radio covered our research on grassland restoration in the Loess Canyons! Read the article [here](https://www.npr.org/sections/pictureshow/2022/06/07/1101257256/neighbors-use-prescribed-fire-to-restore-great-plains-grasslands).

---

May 2022

- Targeted grazing or tree thinning: which best improves forest stand resilience to wildfire (i.e., crown fires)? For answers, check out our [new paper in Ecosphere](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.4061).

---

April 2022

- If you're interested in how large-scale fire and grassland restoration gets done, check out our [AERLive](https://www.britishecologicalsociety.org/applied-ecology-resources/updates-and-events/aer-live/restoration-through-fire-tue-05-apr-2022/) workshop!
- One of our photos made the cover of [Ecological Solutions and Evidence](https://appliedecologistsblog.com/2022/04/26/behind-the-cover-0302/)! 
- Rare birds? Regime shifts? Scale detection via Asymmetric Eigenvector Maps?? Check out our new ms in [Frontiers in Ecology and Evolution](https://www.frontiersin.org/articles/10.3389/fevo.2022.849944/full) if you're interested in a quirky look at spatial resilience.

---

March 2022

- The Wildlife Society covered our paper! Check out their [news feed](https://wildlife.org/for-grassland-birds-the-prescription-is-fire/).

---

February 2022

- Big news!! We got a grant with the US Fish & Wildlife Service to develop a mapping tool to quantify grassland management outcomes. See the new project on the [Research](https://livinglandscapes.github.io/LivingLandscapes_Website/Research.html) page.
- We're hiring two summer technicians!! Check out the [job ad](https://wfscjobs.tamu.edu/jobs/bird-vegetation-survey-technicians-2-for-eastern-arkansas/) for more information.
- Also, if you're interested in ecological resilience and think "wombling" is a hilarious word, check out our new [paper](https://www.sciencedirect.com/science/article/pii/S1470160X22000383) in *Ecological Indicators*.

---

January 2022

- Big, hot, and connected fires restored grassland bird species! Read our new [paper](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1002/2688-8319.12119) in *Ecological Solutions and Evidence* to find out more!
- Lots of press for the Living Landscapes Lab in the New Year: an article in the Wildlife Management Institute's [Outdoor News Bulletin](https://wildlifemanagement.institute/outdoor-news-bulletin/january-2022/restoring-nebraskas-prairie-grasslands-prescribed-burning), a [publication alert](https://www.lpcinitiative.org/publication-alert-spatial-technology-reveals-early-warning-signs-of-large-scale-woody-encroachment-threat-to-greater-prairie-chickens/) and an ["Ask an Expert interview"](https://www.lpcinitiative.org/ask-an-expert-early-warning-signals/) with the Lesser Prairie-Chicken Initiative, and an upcoming press release by University of Arkansas. 

---

December 2021

- Our upcoming paper in *Ecological Solutions and Evidence* on grassland bird responses to prescribed fire was featured in [Discover Magazine](https://www.discovermagazine.com/environment/back-from-the-brink-restoring-prairies-with-fire)! We hope the paper will be published in the New Year!

---

November 2021

- +1 article for November: [Dr. DeGregorio's lab](https://degregoriolab.weebly.com/) and I collaborated to investigate responses of nine-banded armadillo activity patterns to human development/noise. Check it out in [Ecology and Evolution](https://onlinelibrary.wiley.com/doi/10.1002/ece3.8257)!
- Welcome to our new MS student and secretive marshbird expert, Jess Schmit! Jess will start in spring 2022, and she will be co-advised by Caleb and [Dr. Fournier](http://aurielfournier.github.io/about/). Jess will study King Rail migration and habitat usage.
- Our new article in [Ecological Applications](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/eap.2480)
shows how new tech/methods can provide early warnings of woody invasions and help rapidly adapt management. Stay tuned for more press on this one!

---

August 2021

- Mike Shaw will be joining the Living Landscapes Lab this fall too! Mike will be an MS student co-advised by Caleb and [Dr. DeGregorio](https://degregoriolab.weebly.com/) and will study Eastern Spotted Skunk.
- I have another essay out in [Terrain.org](https://www.terrain.org/2021/nonfiction/capture-mark-recapture/)! I talk about my experiences as a person of Hispanic heritage during my first field internship. Check it out if you're interested!

---

June 2021

- Very happy to announce that Percy Marshall will be joining the Living Landscapes Lab this fall! They will be pursuing their MS and studying invasive waterfowl.
- Also, very proud to be a coauthor on another [publication](https://www.ecologyandsociety.org/vol26/iss2/art27/) led by Dr. Donovan! It's the best of our fire + resilience + savanna/grassland ecotone papers yet!

---

May 2021

- We have a new [publication](https://academic.oup.com/jmammal/advance-article-abstract/doi/10.1093/jmammal/gyab035/6254254) in Journal of Mammalogy led by Dr. Victoria Donovan! Check it out if you're interested in bighorn sheep and/or fire.

---

April 2021

- Website launched
- I'm hiring a Master's student for an invasive species ecology and management project! Check out this [link](https://wfscjobs.tamu.edu/jobs/masters-assistantship-invasive-waterfowl-ecology-and-management-arkansas/) for more information.